apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic1
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic-deployment
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 50
